# Mat B træning

Indeholder regneregler, definitioner og opgaver indenfor:

1. [f(x) notation](fx_notation.qmd)
2. [Parenteser](parenteser.qmd)
3. [Ligninger](ligninger.qmd)
4. [Funktioner](funktioner.qmd)
5. [Funktioner og grafer](funktioner_og_grafer.qmd)
6. [Regnearternes hierarki](pemdas.qmd)
7. [Kombinatorik](kombinatorik.qmd)
8. [Enhedscirklen, sinus og cosinus](enhedscirklen.qmd)
9. [Ligningsløsning](ligningsloesning.qmd)
10. [Faktorisering](faktorisering.qmd)
11. [Potenser og rødder](potenser_og_roedder.qmd)
12. [Sandsynlighed](sandsynlighed.qmd)
13. [Reduktion](reduktion.qmd)
14. [Kvadratsætninger](kvadratsaetninger.qmd)
15. [Lineære funktioner](lineaere_funktioner.qmd)
16. [Eksponentiel vækst](eksponentiel_vaekst.qmd)
17. [Potensfunktioner](potensfunktioner.qmd)
18. [Logaritmefunktioner](log_funktioner.qmd)
19. [Procentregning](procent.qmd)
20. [Vektorer](vektorer.qmd)
21. [Skalarprodukt og vinkel mellem vektorer](skalarprodukt.qmd)
22. [Tværvektor, determinant og arealer](tvaervektor.qmd)
23. [Projektion af vektor på vektor](projektion.qmd)
24. [Blandet opgaver med vektorer](vektorer_opsum.qmd)
25. [To ligninger med to ubekendte](toligninger.qmd)
26. [Differentialregning](diff_regning.qmd)  
27. [Tangentensligning](tangent.qmd)
28. [Monotoniforhold](monotoniforhold.qmd)
