# Differentialregning

## Regneregler
- Differentialkvotienten $f'(x_0)$ for funktionen $f$ i tallet $x_0$
$$
f'(x_0) = \lim_{x \to x_0} \frac{f(x)-f(x_0)}{x-x_0}
= \lim_{h \to 0} \frac{f(x_0+h) - f(x_0)}{h}
$$

- Ligning for tangenten $t$ til grafen for $f$ i $P(x_0, f(x_0))$
$$
y = f'(x_0) \cdot (x-x_0) + f(x_0)
$$

- Yderligere regneregler:
    - en funktion gange konstant:
$$
(k \cdot f(x))' = k \cdot f'(x)
$$

    - summen af to funktioner:
$$
(f(x)+g(x))' = f'(x) + g'(x)
$$

    - differancen af to funktioner:
$$
(f(x)-g(x))' = f'(x) - g'(x)
$$

    - produkt af to funktioner (produktreglen/kædereglen):
$$
(f(x) \cdot g(x))' = f'(x) \cdot g(x) + f(x) \cdot g'(x)
$$

    - sammensatte funktioner:
$$
(f(g(x)))' = g'(x) \cdot f'(g(x))
$$

## Afledede funktioner

| Funktionstype | Forskrift | Afledet funktion | 
| --- | --- | --- |
| Lineær funktion | $ax+b$ | $a$ |
| | $k$ | $0$ |
| Logartimefunktion | $\ln(x)$ | $\dfrac{1}{x}=x^{-1}$ |
| Eksponentialfunktioner | $e^x$ | $e^x$ | 
| | $e^{kx}$ | $k \cdot e^{kx}$ | 
| | $a^x$ | $a^x \cdot \ln(a)$ |
| Potensfunktioner | $x^a$ | $a \cdot x^{a-1}$ | 
| | $\dfrac{1}{x}=x^{-1}$ | $-\dfrac{1}{x^2}= -x^{-2}$ |
| | $\sqrt{x}=x^{1/2}$ | $\dfrac{1}{2\sqrt{x}}= \dfrac{1}{2} x^{-1/2}$|
| Trigonometriske funktioner | $\cos(x)$ | $-\sin(x)$ | 
| | $\sin(x)$ | $\cos(x)$ |

::: {.callout-tip}
### Eksempel
Hvis $f(x) = 5x^3-2x^2$, den afledede funktion er: 
$$
f'(x) = (5x^3)' - (2x^2)' 
= 5 \cdot 3x^{3-1} - 2 \cdot 2x^{2-1}
= 15x^2 - 4x 
$$
:::

::: {.callout-tip}
### Eksempel
Hvis $g(x)= x \cdot \ln(x)$, den afledede funktion er:
$$
g'(x)= x' \cdot \ln(x) + x \cdot (\ln(x))'
= 1 \cdot \ln(x) + x \cdot \frac{1}{x}
= \ln(x) +1
$$

:::


##
Differentier følgende funktioner i hånden
$$
\begin{gather}
&
\begin{aligned}
&\text{a.} \ f_1(x) = x^6 \\
&\text{b.} \ f_2(x) = \sqrt{x} \\
&\text{c.} \ f_3(x) = \frac{1}{x} \\
&\text{d.} \ f_4(x) = \cos(x) \\
&\text{e.} \ g_1(x) = 10x^5-7x^3 \\
&\text{f.} \ g_2(x) = \ln(x)+x^2 \\
&\text{g.} \ g_3(x) = 3\sqrt{x}+x^2 \\
&\text{h.} \ g_4(x) = \frac{10}{x} + 12 e^{3x} \\
\end{aligned}
&
\begin{aligned}
&\text{i.} \ h_1(x) = x \cdot \sqrt{x} \\
&\text{j.} \ h_2(x) = \frac{1}{3} \cdot 3^x \\
&\text{k.} \ h_3(x) = (4x^2-2x-5) \cdot e^{5x} \\
&\text{l.} \ h_4(x) = (x^2+3x) \cdot (x^5-4x^2+x) \\
&\text{m.} \ f_1(x) = \sqrt{4x+15} \\
&\text{n.} \ f_2(x) = \frac{1}{-3x+10} \\
&\text{o.} \ f_3(x) = 3\sin(5x-1)+12 \\
&\text{p.} \ f_4(x) = 4e^{-2x-12} \\
\end{aligned}
\end{gather}
$$

##
Beregn nedenstående differentialkvotienter uden brug af CAS
$$
\begin{aligned}
&\text{a.} \ f_1'(2), \text{ når } f_1(x)= x^3 \\
&\text{b.} \ f_2'(4), \text{ når } f_2(x)= \sqrt{x} \\
&\text{c.} \ f_3'(10), \text{ når } f_3(x)= \ln(x) \\
&\text{d.} \ f_4'(-2), \text{ når } f_4(x)= 3x^2-4x+1 \\
&\text{e.} \ g_1'(1), \text{ når } g_1(x)= 7x^3 \cdot \sqrt{x}  \\
&\text{f.} \ g_2'(2), \text{ når } g_2(x)= \sin(3x-6) \\
&\text{g.} \ g_3'(1), \text{ når } g_3(x)= x^2 \cdot \ln(x) \\
&\text{h.} \ g_4'(3), \text{ når } g_4(x)= (3x-4)^5 \\
\end{aligned}
$$

##
Differentier følgende funktioner med CAS

a. $f_1(x)=3x^2+4x-1$
b. $f_2(x)=x^2 \cdot \sin(x)$
c. $f_3(x)=\dfrac{x^2+2x-1}{2x+8}$
d. $f_4(x)=\ln(x^2+1)$

##
Beregn nedenstående differentialkvotienter med CAS

a. $h_1'(-2)$, når $h_1(x)=x^2-5x-12$
b. $h_2'(1)$, når $h_2(x)=\dfrac{\sin(x)}{x}$
c. $h_3'(3)$, når $h_3(x)=\dfrac{100}{1+2\cdot e^{-0.2x}}$
d. $h_4'(5)$, når $h_4(x)=x \cdot (\ln(x))^2$

##
Løs nedenstående ligninger med CAS

a. $f_1'(x)=0$, når $f_1(x)=x^2-5x-12$
b. $f_2'(x)=0$, når $f_2(x)=x^2 \cdot 3^x$
c. $f_3'(x)=0$, når $f_3(x)=\dfrac{x^2-5x+3}{1-4x}$
d. $f_4'(x)=0$, når $f_4(x)=x \cdot (\ln(x))^2$
