# Funktioner og grafer
## Eksempel:
```{python}
import sympy as sp
import seaborn as sns
x=sp.symbols("x")
sns.set()
sns.set_style("whitegrid", {'grid.linestyle': '--'})
sp.plot(
    -0.5*x+5,
    xlim=[-2,8],
    ylim=[-1,7],
    )
pass
```

Den blå linje på figuren viser grafen for funktionen $f$. På figuren kan man aflæse funktionsværdien $f(6)$ xed at finde $x=6$, bevæge sig op til grafen, og dernæst bevæge sig vandret hen til y-aksen.

## Figuren viser grafen for funktionen $g$. Aflæs følgende funktionsværdier. Alle facit er heltal.

```{python}
sns.set()
sns.set_style("whitegrid", {'grid.linestyle': '--'})
sp.plot(
    0.5*x+2,
    xlim=[-2,8],
    ylim=[-1,7],
    )
pass
```

a. $g(2)$
b. $g(0)$
c. $g(6)$
d. $g(8)$

## Figuren viser grafen for funktionen $f$. Aflæs følgende funktionsværdier. Alle facit er heltal.
```{python}
sns.set()
sns.set_style("whitegrid", {'grid.linestyle': '--'})
sp.plot(
    (-1/4)*x*(x-8)+2,
    xlim=[-2,10],
    ylim=[-1,7],
    )
pass
```

a. $f(2)$
b. $f(0)$
c. $f(4)$
d. $f(8)$

## Lad $f(x)=3x-11$
a. Udfyld nedenstående tabel uden CAS

| x | -2 | 0 | 2 | 4 | 6 |
|---|---|---|---|---|---|
|$y=f(x)$| | | | | |

b. Plot punkterne i et koordinatsystem (i hånden), og tjek, at de ligger på en ret linje.

## Figuren viser grafen for funktionen $h$. Løs følgende ligninger vha. grafen. Alle løsninger er et heltal.
```{python}
sns.set()
sns.set_style("whitegrid", {'grid.linestyle': '--'})
sp.plot(
    2*x-7,
    xlim=[-2,10],
    ylim=[-1,7],
    )
pass
``` 

a. $h(x)=1$
b. $h(x)=5$
c. $h(x)=-1$
d. $h(x)=7$

## Figuren viser grafen for funktionen $f$. Løs følgende ligninger ved hjælp af grafen. Alle løsninger er heltal. Nogle a ligningerne har mere en én løsning. Opskriv dem alle.
```{python}
sns.set()
sns.set_style("whitegrid", {'grid.linestyle': '--'})
sp.plot(
    (-1/4)*x*(x-8)+2,
    xlim=[-2,10],
    ylim=[-1,7],
    )
pass
```

a. $f(x)=6$
b. $f(x)=2$
c. $f(x)=5$
d. Hvilken af de følgende ligninger har ingen løsning: $f(x)=0$, eller $f(x)=7$?

## Figuren viser graferne for tre funktioner, $f$, $g$ og $h$. Løs nedenstående ligninger ud fra graferne. Løsningerne er et heltal.

```{python}
sns.set()
sns.set_style("whitegrid", {'grid.linestyle': '--'})
p1 = sp.plot(
    -x+5,
    xlim=[-2,10],
    ylim=[-1,7],
    show=False,
    label="f(x)",
    legend=True
)

p2 = sp.plot(
    0.5*x+2,
    label="g(x)",
    show=False
)

p3 = sp.plot(
    2*x-7,
    label="h(x)",
    show=False
)

p1.append(p2[0])
p1.append(p3[0])

p1.show()

pass
```

a. $g(x)=h(x)$
b. $g(x)=f(x)$
c. $f(x)=h(x)$
