# Kombinatorik
Hvis man både skal vælge blandt $n$ muligheder og bland $m$ muligheder, er der i alt $n\cdot m$ muligheder.

## Eksempel
En restaurant tilbyder 5 forskellige hovedretter og 3 forskellige desserter. En gæst har altså mulighed for at sammensætte hovedret og dessert på $5 \cdot 3 = 15$ forskellige måder.

## Hvor mange forskellige måder kan retterne sammensættes, hvis...
a. en restaurant tilbyder 8 forskellige hovedretter og 2 forskellige desserter?
b. en restaurant tilbyder 7 forskellige hovedretter og 5 forskellige desserter?
c. en restaurant tilbyder 4 forskellige forretter og 2 forskellige hovedretter?
d. en restaurant tilbyder 3 forskellige forretter, 4 forskellige hovedretter og 2 forskellig desserter?

## Hvor mange forskellige kombinationsmuligheder er der?
a. En isbar tilbyder 20 slags is, 5 slags krymmel og 2 slags marmelade.
b. En kodelås har 3 hjul, hver med mulighed for ét  af de 10 cifre: 0, 1, 2, 3, 4, 5, 6, 7, 8 og 9.
c. En nummerplade har 2 bogstaver først og derefter 5 cifre.

## Eksempel
6 elever skal stille sig i kø. Hvor mange forskellige rækkefølger kan de stille sig i? Til plads nummer 1 er der 6 muligheder, til plads nummer 2 er der 5 muligheder, til plads nummer 3 er der 4 muligheder, osv. I alt kan de stille sig i køen på $6 \cdot 5 \cdot 4 \cdot 3 \cdot 2 \cdot 1 = 720$ forskellige måder. 

$6 \cdot 5 \cdot 4 \cdot 3 \cdot 2 \cdot 1$ kan skrives som $6!$, der læses som "6 fakultet". 

## Hvor mange mulige rækkefølger er der hvis:
a. 4 elever skal stille sig i en kø?
b. 8 elever skal stille sig i en kø?
c. 20 elever skal stille sig i en kø?

## Hvor mange forskellige rækkefølger kan hundende komme i mål på, hvis:
a. der er 5 hunde i et hundevæddeløb?
b. der er 9 hunde i et hundevæddeløb?
c. der er 30 hunde i et hundevæddeløb?

## Eksempel - Udvælgelse hvor rækkefølgen er vigtig
Der er 12 heste i et hestvæddeløb. 
På hvor mange måder kan de første 3 pladser fordeles? 
Førstepladsne kan fordeles på 12 forskellige heste. 
Andenpladsen til 11 forskellige, og tredjepladsen til 10 forskellige. 
Der er altså $12 \cdot 11 \cdot 10 = 1320$ forskellige muligheder for fordeling af de første tre pladser.
Det kunne også være beregnet som 
$$
\frac{12!}{(12-3)!}
$$

## Definition
Antallet af måder, man kan udvælge $r$ elementer ud af en større gruppe med $n$ elementer, hvor *rækkefølgen er vigtig*, kan beregnes med formlen
$$
P(n,r) = \frac{n!}{(n-r)!}
$$

##
a. Der er 6 heste i et hestevæddeløb. På hvor mange måder kan de første 3 pladser fordeles?
b. Der er 8 heste i et hestevæddeløb. På hvor mange måder kan de første 5 pladser fordeles?
c. Der er 10 hunde i et hundevæddeløb. På hvor mange måder kan de første 3 pladser fordeles?
d. Der er 120 cykelryttere i et cykelløb. På hvor mange måder kan de første 20 pladser fordeles?
e. Der er 10 gæster til en fest. På hvor mange måder kan vi fordele 7 forskellige festlige hatte? Ingen gæster får mere en en hat, men der er naturligvis ikke hatte til alle.

## Definition - Udvælgelse hvor rækkefølgen er ligegyldig
Antallet af måder, man kan udvælge $r$ elementer ud af en større gruppe med $n$ elementer, hvor *rækkefølgen er ligegyldig*, kan beregnes med formlen
$$
K(n,r) = \frac{n!}{(n-r)!r!}
$$

$K(n,r)$ kaldes en binomialkoefficient, og skrives også nogle gange som $\begin{pmatrix} n \\ r \end{pmatrix}$

## Eksempel
En isbutik har 21 forskellige smagsvarianter. Vi vil gerne have en is med 3 forskellige smagsvarianter. 
Det giver os følgende antal kombinationsmuligheder:
$$
K(21,3) = \frac{21!}{(21-3)!\cdot 3!} = 1330
$$

##
Beregn følgende binomialkoefficienter vha formlen.

a. $K(5,3)$
b. $K(7,2)$
c. $\begin{pmatrix} 6 \\ 2\end{pmatrix}$
d. $K(10,7)$

##
a. Du har 20 par sko, men kan kun tage 3 par med på rejse. Hvor mange kombinationsmuligheder har du?
b. Du har 100 bøger, men kan kun tage 5 med på rejse. Hvor mange kombinationsmuligheder har du?
c. Du har 7 mundharmonikaer, men må kun tage 3 med på festival. Hvor mange kombinationsmuligheder har du?
d. 17 venner holder fest. Der er plads til 4 på altanen. De sidste må være i stuen. På hvor mange måder kan de fordeles?