# Ligninger
Husk at lighedstegnet udtrykker en balance mellem talstørrelserne på hver sit side.

## Eksempel
Løsning af ligningen $2x+10=2\cdot(3x-1)$
$$
\begin{gather}
&
\begin{aligned}
2x+10&=6x-2 \\
2x+10-2x&=6x-2-2x \\
10&=4x-2 \\
10+2&=4x-2+2 \\
12&=4x \\
12/4&=x \\
x&=3
\end{aligned}
&
\begin{aligned}
& \text{2 er ganget ind i parentesen} \\
& \text{2x er trukket fra på begge sider} \\
& \text{Ligningen er reduceret} \\
& \text{2 er lagt til på begge sider} \\
& \text{Ligningen er reduceret} \\
& \text{Begge sider er divideret med 4} \\
& \text{Løsningen er 3}
\end{aligned}
\end{gather}
$$

## 
Løs følgende ligninger i hånden
$$
\begin{gather}
&
\begin{aligned}
& \text{a.} \ x+10=18 \\
& \text{b.} \ x-3=-8 \\
& \text{c.} \ 5x=20 \\
& \text{d.} \ 3x=-9 \\
& \text{e.} \ 4x-7=13 \\
& \text{f.} \ 5x+8=-12 \\
& \text{g.} \ 22=2-4x \\
& \text{h.} \ 3x-5=-17 \\
& \text{i.} \ 2x-7=28-5x \\
& \text{j.} \ 5x-5=-3x-37 \\
& \text{k.} \ 3x-7=-3x+23 \\
& \text{l.} \ 9x+5=2x+40 \\
& \text{m.} \ 3(x-10)=60\\
\end{aligned}
&
\begin{aligned}
& \text{n.} \ 2(x+7)=26 \\
& \text{o.} \ 10=-5(x+3) \\
& \text{p.} \ 36=2(16+2x) \\
& \text{q.} \ 3(x+4)=-2x+32 \\
& \text{r.} \ 6(x-5)=4x-22 \\
& \text{s.} \ 4(3+x)=-(x+13) \\
& \text{t.} \ 6(x+2)=2(2x+10) \\
& \text{u.} \ 5x+12=32 \\
& \text{v.} \ 2x-25=8 \\
& \text{w.} \ 5x+8=3x-2 \\
& \text{x.} \ 2x+4=-3x+29 \\
& \text{y.} \ 2\cdot(x+6)=4 \\
& \text{z.} \ 25=5(x+7) \\
\end{aligned}
\end{gather}
$$

##
Løs følgende ligninger i hånden
$$
\begin{gather}
&
\begin{aligned}
&\text{a.} \ 3(x+4)=-3x-6 \\
&\text{b.} \ 4(x-4)+x=9 \\
&\text{c.} \ \\
&\text{d.} \ \\
&\text{e.} \ \\
&\text{f.} \ \\
&\text{g.} \ \\
&\text{h.} \ \\
&\text{i.} \ \\
&\text{j.} \ \\
&\text{k.} \ \\
&\text{l.} \ \\
&\text{m.} \ \\
\end{aligned}
&
\begin{aligned}
&\text{n.} \ \\
&\text{o.} \ \\
&\text{p.} \ \\
&\text{q.} \ \\
&\text{r.} \ \\
&\text{s.} \ \\
&\text{t.} \ \\
&\text{u.} \ \\
&\text{v.} \ \\
&\text{w.} \ \\
&\text{x.} \ \\
&\text{y.} \ \\
&\text{z.} \ \\
\end{aligned}
\end{gather}
$$

##
Løs følgende andengradsligninger med diskriminantmetoden
$$
\begin{gather}
&
\begin{aligned}
&\text{a.} \ x^2+8x+16=0 \\
&\text{b.} \ 3x^2-3x-6=0 \\
&\text{c.} \ x^2+6x+5=0 \\
&\text{d.} \ x^2+8x-20=0 \\
&\text{e.} \ \\
&\text{f.} \ \\
&\text{g.} \ \\
&\text{h.} \ \\
&\text{i.} \ \\
&\text{j.} \ \\
&\text{k.} \ \\
&\text{l.} \ \\
&\text{m.} \ \\
\end{aligned}
&
\begin{aligned}
&\text{n.} \ \\
&\text{o.} \ \\
&\text{p.} \ \\
&\text{q.} \ \\
&\text{r.} \ \\
&\text{s.} \ \\
&\text{t.} \ \\
&\text{u.} \ \\
&\text{v.} \ \\
&\text{w.} \ \\
&\text{x.} \ \\
&\text{y.} \ \\
&\text{z.} \ \\
\end{aligned}
\end{gather}
$$

## Eksempel - Tjek af løsningen
Vi vil undersøge, om $x=2$ er løsning til tredjegradsligningen $x^3+9x^2+2x-48=0$.

Det gør vi ved indsættelse:
$$
\begin{aligned}
2^3+9\cdot 2^2+2\cdot 2-48&=0 \\
8 + 9 \cdot 4 + 4 - 48 &=0 \\
8+36+4-48 &=0 \\
48-48 &=0 \\
0&=0
\end{aligned}
$$

Vi har vist, at $x=2$ er en løsning.

Hvad med: $x=1$:
$$
\begin{aligned}
1^3+9\cdot 1^2+2\cdot 1-48&=0\\
1+9\cdot 1 + 2 - 48 &=0 \\
1+9+2-48 &=0 \\
36 &\neq 0
\end{aligned}
$$

Vi har vist, at $x=1$ *ikke* er en løsning

##
Tjek ved indsættelse, hvilke af de nedenstående tal der er løsninger til ligningen $x^3+9x^2+6x-16=0$

a. $x=0$
b. $x=1$
c. $x=2$
d. $x=-2$

##
Tjek ved indsættelse, hvilke af de nedenstående tal der er løsninger til ligningen $x^4+4x^3-7x^2-10x=0$

a. $x=0$
b. $x=1$
c. $x=2$
d. $x=-2$

##
Løs nedenstående ligninger med CAS. Vær sikker på, at du får alle løsninger med

a. $2x^3+8x^2-14x-20=0$
b. $x^4+11x^3+14x^2-80x=0$
c. $x^5+24x^4+171x^3+284x^2-480x=0$
d. $x^5-5x^4+10x^3-10x^2+15x-1=0$

## Vink
En $n$-gradspolynomium har op til $n$ løsninger, altså andengradspolynomium har op til 2 løsninger, en tredjegradspolynomium har op til 3 løsninger, osv. 
Graden for et polynomium bestemmes af den højeste potens i ligningen.