project:
  type: book

book:
  title: "Matematik Notesamling og Øvelser"
  author: "Klaudia Anna Kacperska"
  date: "01/17/2024"
  chapters:
    - index.qmd
    - part: første-g.qmd
      chapters:
        - 1-G_supplement/1.pemdas.qmd
        - 1-G_supplement/2.ligninger.qmd
        - 1-G_supplement/3.Reduktion.qmd
        - 1-G_supplement/4.parenteser.qmd
        - 1-G_supplement/5.brøker.qmd
        - 1-G_supplement/6.kvadratsætninger.qmd
        - 1-G_supplement/7.rødder-og-potenser.qmd
        - 1-G_supplement/8.geometriske-formler.qmd
        - 1-G_supplement/9.overslagsregning.qmd
        - 1-G_supplement/10.fremskrivningsfaktor-og-vækstrate.qmd
    - part: 1-G_book/0.index.qmd
      chapters: 
        - 1-G_book/1.modeller-og-variable.qmd
        - 1-G_book/2.lineaere-funktioner.qmd
        - 1-G_book/3.statistik.qmd
    - part: 2-G_supplement/0.index.qmd
      chapters:
        - 2-G_supplement/fx_notation.qmd
        - 2-G_supplement/parenteser.qmd
        - 2-G_supplement/ligninger.qmd
        - 2-G_supplement/funktioner.qmd
        - 2-G_supplement/funktioner_og_grafer.qmd
        - 2-G_supplement/pemdas.qmd
        - 2-G_supplement/kombinatorik.qmd
        - 2-G_supplement/enhedscirklen.qmd
        - 2-G_supplement/ligningsloesning.qmd
        - 2-G_supplement/faktorisering.qmd
        - 2-G_supplement/potenser_og_roedder.qmd
        - 2-G_supplement/sandsynlighed.qmd
        - 2-G_supplement/reduktion.qmd
        - 2-G_supplement/kvadratsaetninger.qmd
        - 2-G_supplement/lineaere_funktioner.qmd
        - 2-G_supplement/eksponentiel_vaekst.qmd
        - 2-G_supplement/potensfunktioner.qmd
        - 2-G_supplement/log_funktioner.qmd
        - 2-G_supplement/procent.qmd
        - 2-G_supplement/vektorer.qmd
        - 2-G_supplement/skalarprodukt.qmd
        - 2-G_supplement/tvaervektor.qmd
        - 2-G_supplement/projektion.qmd
        - 2-G_supplement/vektorer_opsum.qmd
        - 2-G_supplement/toligninger.qmd
        - 2-G_supplement/diff_regning.qmd
        - 2-G_supplement/tangent.qmd
        - 2-G_supplement/monotoniforhold.qmd
    - part: 3-G_supplement/0.index.qmd
      chapters:
        - 3-G_supplement/diff-regning.qmd
    - part: bilag/0.index.qmd
      chapters:
        - bilag/multiplikationstabel.qmd
        - bilag/delelighedsregler.qmd
    


format:
  html:
    theme: cosmo
    number-sections: true
    code-fold: true
    code-block-border-left: false
    output: asis
    page-layout: article
    fig-width: 6
    fig-height: 4
    fig-align: center
    fig-cap-location: margin
  pdf:
    documentclass: scrreprt



